# Generated by Django 3.1.5 on 2021-10-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censustracts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='docket',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='evictions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='judgments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='matowns',
            options={'managed': True},
        ),
    ]
