# Generated by Django 3.1.5 on 2021-10-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211028_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evictions',
            name='city',
        ),
    ]
