# Generated by Django 3.1.5 on 2021-10-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_evictions_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evictions',
            old_name='city_link',
            new_name='city',
        ),
    ]
