# Generated by Django 3.1.5 on 2021-11-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211028_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censusbgs',
            options={'managed': True},
        ),
    ]
