# Generated by Django 3.1.5 on 2021-11-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211103_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusbgs',
            name='ma_town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.matowns'),
        ),
        migrations.AddField(
            model_name='censustracts',
            name='ma_town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.matowns'),
        ),
    ]
