# Generated by Django 3.1.5 on 2021-11-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211103_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censusbgs',
            name='ma_towns',
        ),
        migrations.RemoveField(
            model_name='censustracts',
            name='ma_towns',
        ),
    ]
