# Generated by Django 3.1.5 on 2021-11-03 16:20

from django.db import migrations, models
import django.db.models.deletion


def add_towns_fk(apps, schema_editor):
    Evictions = apps.get_model('app', 'Evictions')
    MaTowns = apps.get_model('app', 'MaTowns')
    for eviction in Evictions.objects.all():
        towns = MaTowns.objects.filter(id=eviction.city.name.upper())
        if len(towns) == 1:
            eviction.town = towns[0]
            eviction.save()


def remove_towns_fk(apps, schema_editor):
    Evictions = apps.get_model('app', 'Evictions')
    for eviction in Evictions:
        eviction.town = None
        eviction.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_auto_20211103_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='evictions',
            name='town',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='app.matowns'),
        ),
        migrations.RunPython(add_towns_fk, remove_towns_fk),
    ]
