# Generated by Django 3.1.5 on 2021-11-03 16:20

from django.db import migrations, models
import django.db.models.deletion


def add_towns_fk(apps, schema_editor):
    City = apps.get_model('app', 'City')
    MaTowns = apps.get_model('app', 'MaTowns')
    for city in City.objects.all():
        towns = MaTowns.objects.filter(id=city.name.upper())
        if len(towns) == 1:
            city.town = towns[0]
            city.save()
        elif len(towns) > 1:
            print(city.id, towns)


def remove_towns_fk(apps, schema_editor):
    City = apps.get_model('app', 'City')
    for city in City:
        city.town = None
        city.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_evictions_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='town',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='app.matowns'),
        ),
        migrations.RunPython(add_towns_fk, remove_towns_fk),
    ]
