# Generated by Django 3.1.5 on 2021-11-04 01:07
from shapely import wkb
from geopandas import gpd
import pandas as pd

from django.db import migrations, models
import django.db.models.deletion


def transform_to_geo(geo):
    return wkb.loads(geo, hex=True)


def add_census_bg(apps, schema_editor):
    Evictions = apps.get_model('app', 'Evictions')
    CensusBgs = apps.get_model('app', 'CensusBgs')
    evictions = Evictions.objects.all().values()
    evictions_df = pd.DataFrame(evictions)
    evictions_gpd = gpd.GeoDataFrame(evictions_df)
    census = CensusBgs.objects.all().values()
    census_df = pd.DataFrame(census)
    census_gpd = gpd.GeoDataFrame(census_df)
    # transform geometry
    evictions_gpd['geometry'] = evictions_gpd['geometry'].transform(transform_to_geo)
    census_gpd['geometry'] = census_gpd['geometry'].transform(transform_to_geo)
    pointInPoly = gpd.sjoin(evictions_gpd, census_gpd, op='within')

    for index, row in pointInPoly.iterrows():
        try:
            eviction = Evictions.objects.get(id=row['id_left'])
            census = CensusBgs.objects.get(id=row['id_right'])
            eviction.census_bg = census
            eviction.save()
        except:
            pass


def remove_census_bg(apps, schema_editor):
    Evictions = apps.get_model('app', 'Evictions')
    for eviction in Evictions.objects.all():
        eviction.census_bg = None
        eviction.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0011_city_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='evictions',
            name='census_bg',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='app.censusbgs'),
        ),
        migrations.RunPython(add_census_bg, remove_census_bg),
    ]
