# Generated by Django 3.1.5 on 2021-11-04 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_city_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='evictions',
            name='census_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.censusbgs'),
        ),
    ]
