# Generated by Django 3.1.5 on 2021-11-15 16:45

from django.db import migrations


def add_towns_to_notowns(apps, schema_editor):
    """
    Connect towns to all evictions with census_bg
    """
    Evictions = apps.get_model('app', 'Evictions')
    notowns = Evictions.objects.filter(town__isnull=True, census_bg__isnull=False)
    for eviction in notowns:
        eviction.town = eviction.census_bg.ma_town
        eviction.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0012_evictions_census_bg'),
    ]

    operations = [
        migrations.RunPython(add_towns_to_notowns),
    ]
